export const mockLeads = [
  {
    id: 1,
    company: "Luma Dental",
    industry: "Dental Clinic",
    city: "Austin",
    country: "USA",
    employees: 18,
    websiteScore: 68,
    estimatedRevenue: 8500,
    opportunity: 92,
  },
  {
    id: 2,
    company: "Bright Smile Clinic",
    industry: "Healthcare",
    city: "Chicago",
    country: "USA",
    employees: 26,
    websiteScore: 55,
    estimatedRevenue: 12000,
    opportunity: 88,
  },
  {
    id: 3,
    company: "Elite Auto Repairs",
    industry: "Automotive",
    city: "Houston",
    country: "USA",
    employees: 12,
    websiteScore: 61,
    estimatedRevenue: 8500,
    opportunity: 80,
  },
  {
    id: 4,
    company: "Skyline Legal",
    industry: "Legal",
    city: "New York",
    country: "USA",
    employees: 42,
    websiteScore: 74,
    estimatedRevenue: 15000,
    opportunity: 81,
  },
  {
    id: 5,
    company: "GreenLeaf Realty",
    industry: "Real Estate",
    city: "Miami",
    country: "USA",
    employees: 19,
    websiteScore: 58,
    estimatedRevenue: 11000,
    opportunity: 90,
  },
  {
    id: 6,
    company: "NorthStar Fitness",
    industry: "Fitness",
    city: "Toronto",
    country: "Canada",
    employees: 35,
    websiteScore: 79,
    estimatedRevenue: 8500,
    opportunity: 76,
  },
];